name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - '**.java'
      - 'build.gradle'
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: secrets

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests with Gradle
        run: ./gradlew clean test
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_EXPIRATION: 360000

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure remote directory exists
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p /home/ubuntu/app/build/libs"

      - name: Copy jar to EC2
        run: scp -i ~/.ssh/id_rsa build/libs/*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/app/build/libs

      - name: Deploy app on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            APP_PATH="/home/ubuntu/app/build/libs/assignment.jar"
            LOG_PATH="/home/ubuntu/app/app.log"
          
            # 종료
            echo "[INFO] 기존 실행 중인 프로세스를 종료합니다"
            pkill -f "$APP_PATH" || echo "No matching java process."
          
            # 실행
            echo "[INFO] 애플리케이션을 실행합니다"
            nohup java \
              -DJWT_SECRET_KEY=$JWT_SECRET_KEY \
              -DJWT_EXPIRATION=$JWT_EXPIRATION \
              -jar "$APP_PATH" > "$LOG_PATH" 2>&1 &
          
            echo "[INFO] 배포 완료. 로그 출력:"
            tail -n 10 "$LOG_PATH"
          EOF