name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때만 배포

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: secrets

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Check EC2_HOST value
        run: echo "Connecting to ${{ secrets.EC2_HOST }}"

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/your-app-dir  # EC2에서 소스코드 위치
            git pull origin main          # 최신 코드 가져오기
            ./deploy.sh                   # 재시작 스크립트 (ex: gradle build & run)
          EOF